Break: Add account name and registration key to HostAgentInfo message
canonical/landscape-hostagent-api pull request #11
Opened 2023-11-21 08:21 UTC by EduardGomezEscandell

The Landscape client sends and `account_name` in order to match the machine to the right account. We need the host to do the same. Similarly, some accounts require a `registration_key`, so it should also be required for the agent.

2023-11-21 09:18 UTC, didrocks approved these changes
As we discussed, LGTM!

2023-11-21 09:26 UTC, didrocks requested changes
Didn’t spot a typo!

2023-11-21 09:26 UTC, didrocks commented on hostagent.proto
> +    string account_name = 5;                // account_name is the acccount used in Landscape SaaS.
```suggestion
    string account_name = 5;                // account_name is the account used in Landscape SaaS.
```

2023-11-21 09:39 UTC, EduardGomezEscandell commented
> Do we really want to send the account name with every refresh list message though or should it be optional?

I guess we don't really need to once we have a UID, but the Landscape team should know better than me.

2023-11-21 18:08 UTC, wck0 commented
The Windows host should include the `account_name` with every message, as well as the `registration_key` if there is one. Then `landscape-server` can decide how to handle the information.

2023-11-21 18:09 UTC, wck0 approved these changes

2023-11-22 07:06 UTC, didrocks approved these changes
Ack then, if you are happy in having it with every single refresh on already established connection, let’s do this!

2023-11-22 07:41 UTC, merged